capa-spi-aws-config/src/main/java/group/rxcloud/capa/spi/aws/config/AwsCapaConfiguration.java
capa-spi-aws-mesh/pom.xml
capa-spi-aws-mesh/src/main/java/group/rxcloud/capa/spi/aws/mesh/config/AwsRpcServiceOptions.java
capa-spi-aws-mesh/src/main/java/group/rxcloud/capa/spi/aws/mesh/config/AwsSpiOptionsLoader.java
capa-spi-aws-mesh/src/main/java/group/rxcloud/capa/spi/aws/mesh/constants/AwsRpcConstants.java
capa-spi-aws-mesh/src/main/java/group/rxcloud/capa/spi/aws/mesh/env/AwsRpcEnvironment.java
capa-spi-aws-mesh/src/main/java/group/rxcloud/capa/spi/aws/mesh/http/AwsCapaHttp.java
capa-spi-aws-mesh/src/main/java/group/rxcloud/capa/spi/aws/mesh/http/serialzer/AwsCapaSerialzerProvider.java
capa-spi-aws-mesh/src/main/java/group/rxcloud/capa/spi/aws/mesh/http/serialzer/BaijiSSJsonObjectSerialzer.java
pom.xml

reliaze rpc invoke in app mesh about aws to aws
#6 

reliaze rpc invoke in app mesh about aws to aws

---

capa-spi-aws-mesh/src/main/java/group/rxcloud/capa/spi/aws/mesh/http/serialzer/AwsCapaSerialzerProvider.java
capa-spi-aws-mesh/src/test/java/group/rxcloud/capa/spi/aws/mesh/config/AwsSpiOptionsLoaderTest.java
capa-spi-aws-mesh/src/test/java/group/rxcloud/capa/spi/aws/mesh/env/AwsRpcEnvironmentTest.java
capa-spi-aws-mesh/src/test/java/group/rxcloud/capa/spi/aws/mesh/http/AwsCapaSerialzerProviderTest.java

add unit test in capa-spi-aws-mesh
#11 

test: add mesh unit test

---

capa-spi-aws-config/src/main/java/group/rxcloud/capa/spi/aws/config/package-info.java
capa-spi-aws-mesh/pom.xml
capa-spi-aws-mesh/src/main/java/group/rxcloud/capa/spi/aws/mesh/config/AwsSpiOptionsLoader.java
capa-spi-aws-mesh/src/main/java/group/rxcloud/capa/spi/aws/mesh/constants/AwsRpcConstants.java
capa-spi-aws-mesh/src/main/java/group/rxcloud/capa/spi/aws/mesh/env/AwsRpcEnvironment.java
capa-spi-aws-mesh/src/main/java/group/rxcloud/capa/spi/aws/mesh/http/AwsCapaHttp.java
capa-spi-aws-mesh/src/main/java/group/rxcloud/capa/spi/aws/mesh/http/serializer/AwsCapaSerializerProvider.java
capa-spi-aws-mesh/src/main/java/group/rxcloud/capa/spi/aws/mesh/http/serializer/BaijiSSJsonObjectSerializer.java
capa-spi-aws-mesh/src/test/java/group/rxcloud/capa/spi/aws/mesh/http/AwsCapaSerialzerProviderTest.java
capa-spi-aws/pom.xml
pom.xml

optimize the rpc-app-mesh code.
https://github.com/reactivegroup/capa-aws/issues/12

refactor: optimize rpc app mesh module

---

capa-spi-aws-mesh/pom.xml
capa-spi-aws-mesh/src/test/java/group/rxcloud/capa/spi/aws/mesh/config/AwsRpcServiceOptionsTest.java
capa-spi-aws-mesh/src/test/java/group/rxcloud/capa/spi/aws/mesh/env/AwsRpcEnvironmentTest.java
capa-spi-aws-mesh/src/test/java/group/rxcloud/capa/spi/aws/mesh/http/AwsCapaHttpTest.java
capa-spi-aws-mesh/src/test/java/group/rxcloud/capa/spi/aws/mesh/http/serializer/AwsCapaSerializerProviderTest.java
capa-spi-aws-mesh/src/test/java/group/rxcloud/capa/spi/aws/mesh/http/serializer/BaijiSSJsonObjectSerializerTest.java
pom.xml

test: add unit test in app mesh
1. AwsCapaHttpTest
2. BaijiSSJsonObjectSerializerTest
3. AwsRpcServiceOptionsTest
#11 

test: add unit test in app mesh

---

capa-spi-aws-mesh/src/main/java/group/rxcloud/capa/spi/aws/mesh/config/AwsRpcServiceOptions.java
capa-spi-aws-mesh/src/main/java/group/rxcloud/capa/spi/aws/mesh/config/AwsSpiOptionsLoader.java
capa-spi-aws-mesh/src/main/java/group/rxcloud/capa/spi/aws/mesh/constants/AwsRpcConstants.java
capa-spi-aws-mesh/src/main/java/group/rxcloud/capa/spi/aws/mesh/env/AwsRpcEnvironment.java
capa-spi-aws-mesh/src/main/java/group/rxcloud/capa/spi/aws/mesh/http/AwsCapaHttp.java
capa-spi-aws-mesh/src/test/java/group/rxcloud/capa/spi/aws/mesh/config/AwsRpcServiceOptionsTest.java
capa-spi-aws-mesh/src/test/java/group/rxcloud/capa/spi/aws/mesh/config/AwsSpiOptionsLoaderTest.java
capa-spi-aws-mesh/src/test/java/group/rxcloud/capa/spi/aws/mesh/env/AwsRpcEnvironmentTest.java

change aws app mesh template
#6 

feat: change aws app mesh template

---

capa-spi-aws-config/pom.xml
capa-spi-aws-config/src/main/java/group/rxcloud/capa/spi/aws/config/AwsCapaConfiguration.java
capa-spi-aws-config/src/main/java/group/rxcloud/capa/spi/aws/config/common/constant/CapaAWSConstants.java
capa-spi-aws-config/src/main/java/group/rxcloud/capa/spi/aws/config/common/enums/FileType.java
capa-spi-aws-config/src/main/java/group/rxcloud/capa/spi/aws/config/common/serializer/DefaultSerializer.java
capa-spi-aws-config/src/main/java/group/rxcloud/capa/spi/aws/config/common/serializer/JsonSerializer.java
capa-spi-aws-config/src/main/java/group/rxcloud/capa/spi/aws/config/common/serializer/PropertiesSerializer.java
capa-spi-aws-config/src/main/java/group/rxcloud/capa/spi/aws/config/common/serializer/Serializer.java
capa-spi-aws-config/src/main/java/group/rxcloud/capa/spi/aws/config/common/serializer/SerializerProcessor.java
capa-spi-aws-config/src/main/java/group/rxcloud/capa/spi/aws/config/entity/Configuration.java
capa-spi-aws-config/src/main/java/group/rxcloud/capa/spi/aws/config/scheduler/AwsCapaConfigurationScheduler.java
capa-spi-aws-config/src/test/java/group/rxcloud/capa/spi/aws/config/AwsCapaConfigurationIgnoreTest.java
capa-spi-aws-config/src/test/java/group/rxcloud/capa/spi/aws/config/User.java
pom.xml

add aws config module code
Please reference the issue this PR will close: #15 
* [√ ] Code compiles correctly

feature:add aws config module

---

capa-spi-aws-config/pom.xml
capa-spi-aws-config/src/main/java/group/rxcloud/capa/spi/aws/config/AwsCapaConfiguration.java
capa-spi-aws-config/src/main/java/group/rxcloud/capa/spi/aws/config/entity/Configuration.java
capa-spi-aws-config/src/main/java/group/rxcloud/capa/spi/aws/config/entity/ConfigurationListener.java
capa-spi-aws-config/src/main/java/group/rxcloud/capa/spi/aws/config/scheduler/AwsCapaConfigurationScheduler.java
capa-spi-aws-infrastructure/pom.xml
capa-spi-aws-mesh/pom.xml
pom.xml

support multiple subscribers listening the same config file change event
Please reference the issue this PR will close: #20 
* [ √] Code compiles correctly

feature:support multiple subscribers for same config file

---

capa-spi-aws-config/pom.xml
capa-spi-aws-config/src/main/java/group/rxcloud/capa/spi/aws/config/AwsCapaConfigStore.java
capa-spi-aws-config/src/main/java/group/rxcloud/capa/spi/aws/config/entity/Configuration.java
capa-spi-aws-config/src/main/java/group/rxcloud/capa/spi/aws/config/serializer/PropertiesSerializer.java
capa-spi-aws-config/src/test/java/group/rxcloud/capa/spi/aws/config/AwsCapaConfigStoreIgnoreTest.java
capa-spi-aws-config/src/test/java/group/rxcloud/capa/spi/aws/config/AwsCapaConfigStoreTest.java
capa-spi-aws-config/src/test/java/group/rxcloud/capa/spi/aws/config/serializer/DefaultSerializerTest.java
capa-spi-aws-config/src/test/java/group/rxcloud/capa/spi/aws/config/serializer/PropertiesSerializerTest.java
pom.xml

1.fix get config bug when the config hasn't been initialized
2.add config ut
Please reference the issue this PR will close: #22 

Fix getconfig bug+add config ut

---

capa-spi-aws-infrastructure/pom.xml
capa-spi-aws-mesh/pom.xml
capa-spi-aws-telemetry/pom.xml
capa-spi-aws-telemetry/src/main/java/group/rxcloud/capa/spi/aws/telemetry/metrics/CloudWatchClientProvider.java
capa-spi-aws-telemetry/src/main/java/group/rxcloud/capa/spi/aws/telemetry/metrics/CloudWatchMetricsExporter.java
capa-spi-aws-telemetry/src/main/java/group/rxcloud/capa/spi/aws/telemetry/metrics/CloundWatchDoubleHistogram.java
capa-spi-aws-telemetry/src/main/java/group/rxcloud/capa/spi/aws/telemetry/metrics/CloundWatchLongHistogram.java
capa-spi-aws-telemetry/src/main/java/group/rxcloud/capa/spi/aws/telemetry/metrics/CollectedMetrics.java
capa-spi-aws-telemetry/src/main/java/group/rxcloud/capa/spi/aws/telemetry/package-info.java
capa-spi-aws-telemetry/src/main/java/group/rxcloud/capa/spi/aws/telemetry/trace/AwsTraceIdGenerator.java
capa-spi-aws-telemetry/src/main/java/group/rxcloud/capa/spi/aws/telemetry/trace/LogSpanProcessor.java
capa-spi-aws-telemetry/src/main/resources/capa-component-telemetry.properties
capa-spi-aws-telemetry/src/main/resources/capa-meter.json
capa-spi-aws-telemetry/src/main/resources/capa-tracer.json
capa-spi-aws-telemetry/src/test/java/group/rxcloud/capa/spi/aws/telemetry/CloudWatchMetricsDemo.java
pom.xml

Trace and metrics implementation on aws.

Trace and metrics implementation on aws.

---

capa-spi-aws-telemetry/pom.xml
capa-spi-aws-telemetry/src/main/java/group/rxcloud/capa/spi/aws/telemetry/log/appender/AbstractCapaAwsLogAppender.java
capa-spi-aws-telemetry/src/main/java/group/rxcloud/capa/spi/aws/telemetry/log/appender/CapaAwsLog4jAppender.java
capa-spi-aws-telemetry/src/main/java/group/rxcloud/capa/spi/aws/telemetry/log/appender/CapaAwsLogbackAppender.java
capa-spi-aws-telemetry/src/main/java/group/rxcloud/capa/spi/aws/telemetry/log/service/CloudWatchLogsService.java
capa-spi-aws-telemetry/src/main/resources/capa-component-log.properties
pom.xml

Feat add aws logs impl

---

capa-spi-aws-log/pom.xml
capa-spi-aws-telemetry/pom.xml

update log4j version

---

pom.xml

Please reference the issue this PR will close: #_[issue number]_

update capa version

---

capa-spi-aws-log/src/main/java/group/rxcloud/capa/spi/aws/log/service/CloudWatchLogsService.java

Fix exception 

---

capa-spi-aws-log/pom.xml
capa-spi-aws-telemetry/pom.xml

update logback version

---

capa-spi-aws-config/pom.xml
capa-spi-aws-config/src/main/java/group/rxcloud/capa/spi/aws/config/AwsCapaConfigStore.java
capa-spi-aws-config/src/test/java/group/rxcloud/capa/spi/aws/config/AwsCapaConfigStoreIgnoreTest.java
pom.xml

Please reference the issue this PR will close: #41 
* [√ ] Code compiles correctly
* [√  ] Created/updated tests
* [√  ] Extended the documentation

feature:get env from foundation in config

---

capa-spi-aws-config/src/test/java/group/rxcloud/capa/spi/aws/config/AwsCapaConfigStoreTest.java

Please reference the issue this PR will close: #49
* [ √] Code compiles correctly
* [√ ] Created/updated tests
* [ √] Extended the documentation

fix:fix config ut

---

capa-spi-aws-config/pom.xml
capa-spi-aws-infrastructure/pom.xml
capa-spi-aws-log/pom.xml
capa-spi-aws-mesh/pom.xml
capa-spi-aws-telemetry/pom.xml
capa-spi-aws-telemetry/src/main/java/group/rxcloud/capa/spi/aws/telemetry/metrics/CloudWatchClientProvider.java
pom.xml

Remove the region param when init cloud watch metric client.

Remove the region param when init cloud watch metric client.

---

capa-spi-aws-telemetry/src/main/java/group/rxcloud/capa/spi/aws/telemetry/metrics/CloudWatchMetricsExporter.java

Add length restrict with dimension value.
Reset the list after flushing.

Add length restrict with dimension value.

---

capa-spi-aws-config/pom.xml
capa-spi-aws-log/pom.xml
capa-spi-aws-mesh/pom.xml
capa-spi-aws-telemetry/pom.xml
pom.xml

+ refactor pom
https://github.com/reactivegroup/capa-aws/issues/12

refactor: refactor pom

---

capa-spi-aws-config/pom.xml
capa-spi-aws-log/pom.xml
capa-spi-aws-mesh/pom.xml
capa-spi-aws-telemetry/pom.xml
capa-spi-aws-telemetry/src/main/java/group/rxcloud/capa/spi/aws/telemetry/metrics/CloudWatchMetricsExporter.java
pom.xml

merge master

---

capa-spi-aws-config/pom.xml
capa-spi-aws-infrastructure/pom.xml
capa-spi-aws-log/pom.xml
capa-spi-aws-log/src/main/java/group/rxcloud/capa/spi/aws/log/handle/MessageManager.java
capa-spi-aws-log/src/main/java/group/rxcloud/capa/spi/aws/log/handle/MessageSender.java
capa-spi-aws-mesh/pom.xml
capa-spi-aws-telemetry/pom.xml
pom.xml

update pom version

---

capa-spi-aws-telemetry/src/main/java/group/rxcloud/capa/spi/aws/telemetry/metrics/CloudWatchMetricsExporter.java

Use delta agg.

---

capa-spi-aws-log/src/main/java/group/rxcloud/capa/spi/aws/log/appender/CapaAwsLog4jAppender.java
capa-spi-aws-log/src/main/java/group/rxcloud/capa/spi/aws/log/appender/CapaAwsLogbackAppender.java
capa-spi-aws-log/src/main/java/group/rxcloud/capa/spi/aws/log/configuration/LogConfiguration.java
capa-spi-aws-log/src/main/java/group/rxcloud/capa/spi/aws/log/enums/CapaLogLevel.java
capa-spi-aws-log/src/main/java/group/rxcloud/capa/spi/aws/log/manager/LogManager.java
capa-spi-aws-log/src/main/java/group/rxcloud/capa/spi/aws/log/service/CloudWatchLogsService.java
example/pom.xml
example/src/main/java/group/rxcloud/capa/spi/aws/log/DemoLog.java
example/src/main/resources/META-INF/app.properties
example/src/main/resources/logback.xml
pom.xml

Lower the log adjustment level to the aws implementation part.

Lower the log adjustment level to the aws implementation part.

---

capa-spi-aws-config/src/main/java/group/rxcloud/capa/spi/aws/config/AwsCapaConfigStore.java
capa-spi-aws-config/src/main/java/group/rxcloud/capa/spi/aws/config/serializer/JsonSerializer.java
capa-spi-aws-log/src/main/java/group/rxcloud/capa/spi/aws/log/service/CloudWatchLogsService.java
capa-spi-aws-telemetry/src/main/java/group/rxcloud/capa/spi/aws/telemetry/metrics/CloudWatchMetricsExporter.java
pom.xml

Please reference the issue this PR will close: #65 
* [ √] Code compiles correctly
* [ √] Created/updated tests
* [ √] Extended the documentation

feature:1.modify config log level;2.update addons version

---

capa-spi-aws-config/pom.xml
capa-spi-aws-infrastructure/pom.xml
capa-spi-aws-log/pom.xml
capa-spi-aws-log/src/main/java/group/rxcloud/capa/spi/aws/log/handle/MessageSender.java
capa-spi-aws-mesh/pom.xml
capa-spi-aws-telemetry/pom.xml
capa-spi-aws-telemetry/src/main/java/group/rxcloud/capa/spi/aws/telemetry/trace/AwsWebContextPropagatorLoader.java
example/pom.xml
pom.xml

1.Upgrade capa version to 1.10.12.
2.Adjust time args of log message sender.

1.Upgrade capa version to 1.10.12.

---

capa-spi-aws-log/src/main/java/group/rxcloud/capa/spi/aws/log/service/CloudWatchLogsService.java
example/src/main/java/group/rxcloud/capa/spi/aws/log/DemoLog.java

style: upgrade the log stream name

---

capa-spi-aws-config/pom.xml
capa-spi-aws-infrastructure/pom.xml
capa-spi-aws-log/pom.xml
capa-spi-aws-log/src/main/java/group/rxcloud/capa/spi/aws/log/service/CloudWatchLogsService.java
capa-spi-aws-mesh/pom.xml
capa-spi-aws-telemetry/pom.xml
example/pom.xml
pom.xml

Replace netty dependencies into netty-all.
Replace commons-logging into jcl-over-slf4j.

Update version to 1.10.12.2.RELEASE

---

capa-spi-aws-config/pom.xml
capa-spi-aws-config/src/test/java/group/rxcloud/capa/spi/aws/config/AwsCapaConfigStoreTest.java
capa-spi-aws-infrastructure/pom.xml
capa-spi-aws-infrastructure/src/main/java/group/rxcloud/capa/spi/aws/infrastructure/AwsCapaEnvironment.java
capa-spi-aws-log/pom.xml
capa-spi-aws-mesh/src/main/java/group/rxcloud/capa/spi/aws/mesh/AwsCapaRpcProperties.java
capa-spi-aws-mesh/src/main/java/group/rxcloud/capa/spi/aws/mesh/http/AwsCapaHttp.java
capa-spi-aws-mesh/src/main/resources/capa-component-rpc-aws.properties
capa-spi-aws-mesh/src/test/java/group/rxcloud/capa/spi/aws/mesh/env/AwsRpcEnvironmentTest.java
capa-spi-aws-mesh/src/test/java/group/rxcloud/capa/spi/aws/mesh/http/AwsCapaHttpTest.java
capa-spi-aws-mesh/src/test/java/group/rxcloud/capa/spi/aws/mesh/http/config/AwsRpcServiceOptionsTest.java
capa-spi-aws-mesh/src/test/java/group/rxcloud/capa/spi/aws/mesh/http/config/AwsSpiOptionsLoaderTest.java
capa-spi-aws-telemetry/pom.xml
pom.xml

rpc add accept header
Please reference the issue this PR will close: #_[issue number]_

feat: rpc add accept header

---

capa-spi-aws-config/pom.xml
capa-spi-aws-infrastructure/pom.xml
capa-spi-aws-log/pom.xml
capa-spi-aws-log/src/main/java/group/rxcloud/capa/spi/aws/log/appender/CapaAwsLog4jAppender.java
capa-spi-aws-log/src/main/java/group/rxcloud/capa/spi/aws/log/appender/CapaAwsLogbackAppender.java
capa-spi-aws-mesh/pom.xml
capa-spi-aws-telemetry/pom.xml
example/pom.xml
pom.xml

Resolve recursive dependency in log appender.

Resolve recursive dependency in log appender.

---

capa-spi-aws-config/src/main/java/group/rxcloud/capa/spi/aws/config/serializer/PropertiesSerializer.java

Please reference the issue this PR will close: #_[issue number]_

Feature:properties文件返回hashmap格式map

---

capa-spi-aws-config/src/main/java/group/rxcloud/capa/spi/aws/config/AwsCapaConfigStore.java

Please reference the issue this PR will close: #_[issue number]_

chore:change config log level to warn

---

capa-spi-aws-config/pom.xml
capa-spi-aws-infrastructure/pom.xml
capa-spi-aws-log/pom.xml
capa-spi-aws-log/src/main/java/group/rxcloud/capa/spi/aws/log/plugin/AwsLogPlugin.java
capa-spi-aws-log/src/main/resources/META-INF/services/group.rxcloud.capa.addons.cat.CatLogPlugin
capa-spi-aws-mesh/pom.xml
capa-spi-aws-telemetry/pom.xml
example/pom.xml
pom.xml

Add cat log plugin

---

capa-spi-aws-config/pom.xml
capa-spi-aws-infrastructure/pom.xml
capa-spi-aws-log/pom.xml
capa-spi-aws-log/src/main/java/group/rxcloud/capa/spi/aws/log/appender/CapaLogEvent.java
capa-spi-aws-log/src/main/java/group/rxcloud/capa/spi/aws/log/filter/logoutput/LogOutputCountFilter.java
capa-spi-aws-log/src/main/java/group/rxcloud/capa/spi/aws/log/handle/MessageSender.java
capa-spi-aws-log/src/main/java/group/rxcloud/capa/spi/aws/log/manager/CustomLogManager.java
capa-spi-aws-log/src/main/java/group/rxcloud/capa/spi/aws/log/manager/LogAppendManager.java
capa-spi-aws-log/src/main/java/group/rxcloud/capa/spi/aws/log/service/CloudWatchLogsService.java
capa-spi-aws-log/src/main/java/group/rxcloud/capa/spi/aws/log/service/LogMetrics.java
capa-spi-aws-mesh/pom.xml
capa-spi-aws-telemetry/pom.xml
capa-spi-aws-telemetry/src/main/java/group/rxcloud/capa/spi/aws/telemetry/trace/LogSpanProcessor.java
example/pom.xml
pom.xml

1.Use log instead of metrics for log throttle alerting.
2.Change the format of all the common tag key. (eg. _aa_bb)
3.Delete unused code.

Log Throttle optimize.
